// Next
import Head from "next/head";
import { NextPage } from "next";

// Components
import AuthButton from "components/ui/AuthButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NFT Generate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthButton />
    </div>
  );
};

export default Home;
